//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.SectionSchedules = new HashSet<SectionSchedule>();
            this.SectionSubTemplates = new HashSet<SectionSubTemplate>();
            this.StudentTranscripts = new HashSet<StudentTranscript>();
        }
    
        public string SectionNo { get; set; }
        public int SeatingCapacity { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ProfessorCode { get; set; }
        public string RepresentedSubject { get; set; }
        public int SemesterBelong { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual ICollection<SectionSchedule> SectionSchedules { get; set; }
        public virtual ICollection<SectionSubTemplate> SectionSubTemplates { get; set; }
        public virtual ICollection<StudentTranscript> StudentTranscripts { get; set; }
    }
}
