//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionSchedule
    {
        public SectionSchedule()
        {
            this.TranscriptAttendaceEntries = new HashSet<TranscriptAttendaceEntry>();
        }
    
        public int SectionScheduleID { get; set; }
        public string SectionID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Slot { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Room { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual ICollection<TranscriptAttendaceEntry> TranscriptAttendaceEntries { get; set; }
    }
}
