//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDEMO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class studentdataEntities : DbContext
    {
        public studentdataEntities()
            : base("name=studentdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<PrequisiteManager> PrequisiteManagers { get; set; }
        public DbSet<Professor> Professors { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<SectionSchedule> SectionSchedules { get; set; }
        public DbSet<SectionSubTemplate> SectionSubTemplates { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentTranscript> StudentTranscripts { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<SubjectTemplate> SubjectTemplates { get; set; }
        public DbSet<TranscriptAttendaceEntry> TranscriptAttendaceEntries { get; set; }
        public DbSet<TranscriptMarkEntry> TranscriptMarkEntries { get; set; }
    }
}
