//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.PrequisiteManagers = new HashSet<PrequisiteManager>();
            this.PrequisiteManagers1 = new HashSet<PrequisiteManager>();
            this.Sections = new HashSet<Section>();
            this.SubjectTemplates = new HashSet<SubjectTemplate>();
        }
    
        public string SubjectCode { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> Credit { get; set; }
    
        public virtual ICollection<PrequisiteManager> PrequisiteManagers { get; set; }
        public virtual ICollection<PrequisiteManager> PrequisiteManagers1 { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<SubjectTemplate> SubjectTemplates { get; set; }
    }
}
