//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIDEMO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranscriptAttendaceEntry
    {
        public int EntryID { get; set; }
        public int TranscriptID { get; set; }
        public Nullable<int> AttendanceStatus { get; set; }
        public int SectionScheduleID { get; set; }
    
        public virtual SectionSchedule SectionSchedule { get; set; }
        public virtual StudentTranscript StudentTranscript { get; set; }
    }
}
